version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "America/Los_Angeles"
